name: 'local_bump'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # 4am, daily

jobs:
  local_bump:
    uses: 'azurystudio/bump/.github/workflows/bump.yml@dev'
    with:
      reviewers: 'unvented'
    secrets:
      token: '${{ secrets.GITHUB_TOKEN }}'
